"""empty message

Revision ID: 6e1c0bb3b678
Revises: a744d67a2cbb
Create Date: 2024-11-03 21:06:51.685982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1c0bb3b678'
down_revision = 'a744d67a2cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clue_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('clue_index', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('clues',
               existing_type=sa.TEXT(),
               type_=sa.PickleType(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('about')
        batch_op.drop_column('name')
        batch_op.drop_column('age')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('about', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('clues',
               existing_type=sa.PickleType(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('clue_access')
    # ### end Alembic commands ###
