"""empty message

Revision ID: 823fbb23db2a
Revises: c2cfc2fe00d4
Create Date: 2024-11-03 21:43:22.909388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823fbb23db2a'
down_revision = 'c2cfc2fe00d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clue_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clue_no', sa.Integer(), nullable=False))
        batch_op.drop_column('clue_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clue_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clue_index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('clue_no')

    # ### end Alembic commands ###
