"""empty message

Revision ID: c2cfc2fe00d4
Revises: f020bd23187c
Create Date: 2024-11-03 21:32:42.248260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cfc2fe00d4'
down_revision = 'f020bd23187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clan_clue_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_clue_access',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clan_id', sa.INTEGER(), nullable=True),
    sa.Column('clue_no', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
