"""empty message

Revision ID: f020bd23187c
Revises: 72d9e5690e46
Create Date: 2024-11-03 21:10:56.579208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f020bd23187c'
down_revision = '72d9e5690e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_clue_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('clue_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clan_clue_access')
    # ### end Alembic commands ###
